# must add pre-commit pip package. Then run pre-commit install
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Organize imports (isort rules)
      - id: ruff
        name: ruff (fix imports)
        args: [check, --select, I, --fix]

      # Format code (ruff formatter)
      - id: ruff-format
        name: ruff-format


#repos:
#  - repo: local
#    hooks:
#      - id: ty
#        name: ty (uvx)
#        entry: uvx ty check .
#        language: system
#        pass_filenames: false

