# must add pre-commit pip package. Then run pre-commit install
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: []
      - id: ruff-format

#repos:
#  - repo: local
#    hooks:
#      - id: ty
#        name: ty (uvx)
#        entry: uvx ty check .
#        language: system
#        pass_filenames: false

